### ISSUE TITLE
types.proto missing import

### ISSUE THREAD

**Issue by mdyring** [tendermint/abci#179] opened 2018-01-12 19:02 UTC
The import github.com/gogo/protobuf/gogoproto/gogo.proto doesn't exist which causes protoc to complain.

In addition some concerns from Matrix chat that would be nice to address:

srmo: Could someone elaborate ob the new gogo types in the abci protobuf types definition? It became pretty difficult to port this to non go languages. Are those new types required? What happens if we leave them out? What are you using them for?

mdyring: We should probably open an issue for it, I haven't tested yet on C++.. But are you seeing build errors?

srmo: @mdyring i had to do crazy workarounds to generate the class files in java which worked but i had no idea why. Someone opened a PR with the gogoproto stuff removed, which has no side effects in simple test cases but this isn’t really providing confidence. A issue seems the way to go.

**Comment by sbellem** [comment] 2018-01-16 22:15
We ran into this issue meanwhile trying to upgrade the Python ABCI project, and so far I have not found a straightforward solution. 

The CockroachDB project had a similar [issue](https://github.com/cockroachdb/cockroach/issues/393) and seemingly resolved it by making gogo-free proto files.

In another related [issue](https://github.com/prometheus/prometheus/issues/3270#issuecomment-335821242), on the Prometheus project, performance is given as a key reason:

> With the state of things, not using gogoproto is simply not an option from a performance and code sanity perspective.

it is suggested to remove the language specific annotations:

> The only reasonable answer right now is to copy the file, strip all annotations and potentially replace them with annotations for the language of your choice. It's an awful user experience. But that's for the protobuf/grpc community to figure out.

**Comment by srmo** [comment] 2018-01-16 22:18
thanks @sbellem for the links to similar issues. I'll look into the last two points. We have the same problem with the java port.

**Comment by sbellem** [comment] 2018-01-16 22:20
> thanks @sbellem for the links to similar issues. I'll look into the last two points. We have the same problem with the java port.

Thanks to you too! I saw the issue on `jabci` and it was useful, as it at least confirmed I was not alone! :)

**Comment by srmo** [comment] 2018-01-16 22:25
:) yep, that's always a good feeling

**Comment by johndpope** [comment] 2018-01-17 09:35
FYI  this maybe of some use. https://github.com/tendermint/abci/tree/master/types/protoreplace This I understand predates gogo/profobuffer. Perhaps need to just trawl proto file history to find a working file.

**Comment by sbellem** [comment] 2018-01-17 14:32
> FYI this maybe of some use. https://github.com/tendermint/abci/tree/master/types/protoreplace

Thanks @johndpope.

**Comment by ebuchman** [comment] 2018-05-14 23:29
Yikes! Sorry we seemed to have missed this earlier.

Did anyone not manage to get it figured out? Seems a few projects have just copied and stripped the annotations, but obviously that's not sustainable.

We'll look into this. Perhaps we can just get rid of gogo; since anyone looking for performance in Go can just compile the app in with Tendermint, we shouldn't have the same performance requirement there as eg. Prometheus.

Sorry for all the trouble.

**Comment by ebuchman** [comment] 2018-06-01 01:46
Closing for https://github.com/tendermint/abci/issues/256

**Closed by ebuchman** 2018-06-01 01:46 UTC
Labels: priority?
