### ISSUE TITLE
`go get` doesn't work

### ISSUE THREAD

**Issue by raffomania** [tendermint/abci#225] opened 2018-04-06 17:56 UTC
When I run 

    go get github.com/tendermint/abci

I get the following error:

    can't load package: package github.com/tendermint/abci: no Go files in /home/charlie/.go/src/github.com/tendermint/abci

**Comment by ebuchman** [comment] 2018-04-06 20:17
Expected behaviour. There's no top level Go files. Did you see instructions somewhere that suggested you could just `go get` this ? You should be able to `go get github.com/tendermint/abci/cmd/abci-cli`, but we can't guarantee that always works because dependencies might be out of sync. Proper thing to do is use `glide install` from the directory once its been git clones (`go get` will git clone it to the right spot even if it throws that error).

Closing this. Let us know if you still have troubles.

**Closed by ebuchman** 2018-04-06 20:17 UTC
