### ISSUE TITLE
abci-cli console produces empty output for some commands

### ISSUE THREAD

**Issue by melekes** [tendermint/abci#75] opened 2017-04-21 14:01 UTC
https://tendermint.com/docs/guides/abci-cli

dummy app running in another process.

abci-cli console:

```
> echo hello
-> data: hello
-> data.hex: 68656C6C6F

> commit

> deliver_tx "abc"

> commit
-> data: u~׈$E
              -> data.hex: 750502FC7E84BBD788ED589624F06CFA871845D1

> query "abc"
-> log: exists
-> height: 0
-> value: abc
-> value.hex: 616263
```

both on master and develop https://github.com/tendermint/abci/commit/56e13d87f4e3ec1ea756957d6b23caa6ebcf0998

**Comment by ebuchman** [comment] 2017-04-21 16:42
This happens if the data is empty. Should we just print `-> data: ` if its empty?

**Comment by melekes** [comment] 2017-04-21 16:44
Yeah, much better than an empty string

**Comment by zramsay** [comment] 2017-10-20 12:01
sort of duplicate of #93 (similar enough anyways). I'll pick them both up

**Closed by zramsay** 2017-10-20 12:01 UTC
Labels: Type: Enhancement
