### ISSUE TITLE
Update glide.yaml to point to versioned releases for the tendermint libraries

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/abci#67] opened 2017-03-30 01:26 UTC
This can cause dependency conflicts in other packages, think it makes sense to try to update the dependent master branches from their respective develop branches and upgrade acbi here.

**Comment by rigelrozanski** [comment] 2017-03-30 01:27
One glide update conflict I've come across is rooted from abci importing develop branch of go-crypto

**Comment by ethanfrey** [comment] 2017-03-30 09:53
Since we only push to master on release, these should all be tagged versions. So when I check out an old version of abci and compile, it uses v0. 8.0 of tendermint or whatever, not just the most recent master branch. 

For this to work well, we need to version all repos and declare the numbers in master, updating on releases. This will be easier when bucky merges all repos together

**Comment by adrianbrink** [comment] 2017-04-20 12:32
It would also give us the ability to actually go back in time and reproduce old builds very easily.

tags: devops

**Comment by adrianbrink** [comment] 2017-05-08 10:16
@ebuchman Has this been fixed with the recent merging of the repos?

**Comment by ebuchman** [comment] 2017-05-08 19:37
Ok all libs are versioned now: abci, go-crypto, go-wire, tmlibs, and merkleeyes. All other libraries are being deprecated and dont need versions (folks can just use master/develop). 

So, we should have glide pointing to proper versions in our releases? Rather than just `develop` ? And we revert back to `develop` after the release and pushed ?

**Comment by adrianbrink** [comment] 2017-05-08 21:51
Okay, so that we always develop with the newest version of our libraries, but our releases only ever use specific version of libraries, correct?

**Comment by ebuchman** [comment] 2017-05-09 21:23
That's the idea!

**Comment by zramsay** [comment] 2017-09-05 20:10
see #105

**Closed by zramsay** 2017-09-05 20:10 UTC
Labels: Type: Enhancement
